-- Migration 008: Create products_catalog_view - SUPERSEDED, intentionally empty.
--
-- This used to create products_catalog_view (UNION ALL of the 8 category
-- tables). Later migrations added columns to the view, and Postgres can't
-- CREATE OR REPLACE a view with fewer columns than it already has, so
-- re-running this old definition failed on every sync-schema run.
--
-- The view is now defined in one place - migration 016 - which runs after
-- the columns it needs exist (012 adds the sale columns, 016 the minimum
-- order column). No migration between 008 and 016 uses the view.
